### ISSUE TITLE
boxcryptor-single-file-encryptor?

### ISSUE THREAD

**Issue by ink-splatters** [secomba/boxcryptor-single-file-decryptor#6]
Hi there,

I understand that given you have opened the decryption code, it's not rocket science for one to build encryption either, but still, it would be really nice if you'd open the encryptor as well!

Thanks,
Peter

**Comment by colbri77** [comment]
Hi Peter,

thank you for your suggestion. The main purpose of the single-file-decryptor is to provide an addition to our encryption scheme's documentation (https://www.boxcryptor.com/en/technical-overview/). Through this code, users can quickly verify that Boxcryptor actually works the way stated on our website by decrypting their files through it and reviewing the source code.

For that purpose, an additional encryptor would add little additional value. But I understand that some users might have some particular use cases that would make an encryptor useful. We'll keep your suggestion in mind.

Best regards,
  Christian
